version: '3.9'

services:
    consul:
        ports:
             - "8500:8500"

    novasaasadminapi1:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ServiceConfig__Id=novasaasadminapi-9100
          - ServiceConfig__Name=novasaasadminapi
          - ServiceConfig__DiscoveryAddress=http://consul:8500
          - ServiceConfig__Address=novasaasadminapi1
          - ServiceConfig__Port=80
          - ServiceConfig__HealthCheckEndPoint=healthcheck
        ports:
            - 9100:80
        depends_on:
            - consul

    novasaasadminapi2:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ServiceConfig__Id=novasaasadminapi-9200
          - ServiceConfig__Name=novasaasadminapi
          - ServiceConfig__DiscoveryAddress=http://consul:8500
          - ServiceConfig__Address=novasaasadminapi2
          - ServiceConfig__Port=80
          - ServiceConfig__HealthCheckEndPoint=healthcheck
        ports:
            - 9200:80
        depends_on:
            - consul

    novasaasadminapi3:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ServiceConfig__Id=novasaasadminapi-9300
          - ServiceConfig__Name=novasaasadminapi
          - ServiceConfig__DiscoveryAddress=http://consul:8500
          - ServiceConfig__Address=novasaasadminapi3
          - ServiceConfig__Port=80
          - ServiceConfig__HealthCheckEndPoint=healthcheck
        ports:
            - 9300:80
        depends_on:
            - consul

    novasaasservicesgateway:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
        ports:
            - 9500:80
        depends_on:
            - consul
            - novasaasadminapi1
            - novasaasadminapi2
            - novasaasadminapi3
