name: Nova.SaaS.Admin.Api Build Pipeline
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checking Out Code
      uses: actions/checkout@v2
    - name: Installing .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.300
        include-prerelease: true
    - name: Restoring Nuget Packages
      run: dotnet restore NovaSaaSFramework.sln
    - name: Building Project
      run: dotnet build NovaSaaSFramework.sln -c Release
